services:

  admin:
    build: admin
    depends_on:
      - admin-db
    ports:
      - "80:3031"

  admin-db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=pda
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_PASSWORD=pda
      - POSTGRES_USER=pda

  authoritative:
    build: authoritative
    depends_on:
      - authoritative-db
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"

  authoritative-db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=pdns
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_PASSWORD=pdns
      - POSTGRES_USER=pdns

  dnsdist:
    build: dnsdist
    environment:
      - DNSDIST_PLAIN=yes
      - DNSDIST_QUIET=no
    ports:
      - "2053:53/tcp"
      - "2053:53/udp"

  recursor:
    build: recursor
    environment:
      - RECURSOR_QUIET=false
    sysctls:
      - net.ipv6.route.max_size=16384
    ports:
      - "3053:53/tcp"
      - "3053:53/udp"
